---
title: "Analysis of Energy Inefficiency in Chicago"
author: "James Harren (GitHub user: james-harren) - Section 1"
date: "March 5, 2026"
format:
  pdf:
    include-in-header:
      text: |
        % Enable wrapping for Pandoc code blocks in PDF
        \usepackage{fvextra}
        \usepackage{float}
        \usepackage{makecell}
        \usepackage{booktabs}
        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
editor: source
execute-dir: project
---

```{python}
#| eval: true
#| echo: false

# imports
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import os
from shapely import wkt
import altair as alt
alt.data_transformers.disable_max_rows()
alt.renderers.enable("png")
import warnings
warnings.filterwarnings('ignore')
```

## Background

The City of Chicago values energy efficiency as a means to decrease carbon emissions and improve comfort of homes for Chicagoans. The city's [Climate Action Plan](https://www.chicago.gov/content/dam/city/sites/climate-action-plan/documents/Chicago-CAP-071822.pdf) asserts that carbon emissions from existing buildings are substantial at 69% of total emissions, and energy efficiency programs are important to prioritize.. 

Already the city, through the [Building Energy Use Benchmarking Ordinance](https://www.chicago.gov/city/en/depts/env/supp_info/energy-benchmarking.html), requries buildings over 50,000 square feet to report energy use as an energy efficiency initiative. 

The city's Department of Housing adminsters a grant program that aims to help retrofit chicago homes, the [Green Homes Chicago Program](https://www.chicago.gov/city/en/depts/doh/provdrs/homeowners/svcs/green-homes-chicago.html) which provides low income homeowners free energy efficiency upgrades. Future iterations of the program may benefit from different program designs to achieve more energy efficiency benefits per grant dollar. Additionaly, it is important to know if the target grantee is the most 'efficient' target in terms of energy efficiency benefits that can be achieved per dollar. 

## Research Question

What kinds of neighborhoods have the worst energy efficiency and what areas have the greatest energy efficiency outreach potential?

## Approach

In order to understand what kinds of groups may benefit from energy efficiency programs the most, energy data from the City of Chicago and income data from the American Community Survey from the U.S. Census were analyzed at the Community Area level. Chicago has published energy use data from 2010 aggregated to the census block level and includes both electricity and gas use aggregated to the census block level and information on the buildings within the census block. 

Different energy efficiency metrics were calculated at the census block level. First, in order to estimate how insulated a building is, a difference in seasonal gas usage metric was calculated by taking the difference between January, the highest average gas use month, and August, the lowest average gas use month, and dividing by the square footage of the building stock in the census block to be able to compare across geographies. Second, in order to measure how inefficient appliances are, total electricity use for the year is divided by the square footage of the building stock int he census block to compare across geographies. 

Data were then combined with income data and aggregated to the community area level. The mean of energy efficiency metrics and average building age were weighted on square footage, and percent renter population and income were weighed on population. Finally, geography of the community areas were merged into the final dataset.

```{python}
#| eval: true
#| echo: false

energy_use = pd.read_csv('data/external/Energy_Usage_2010.csv')

# RESIDENTIAL PROPERTIES
energy_use = energy_use[energy_use["BUILDING TYPE"]=='Residential']

# KWH PER SQFT
energy_use['TOTAL KWH'] = energy_use['TOTAL KWH'].str.replace(',', '').astype(float)
energy_use['KWH TOTAL SQFT'] = energy_use['KWH TOTAL SQFT'].str.replace(',', '').astype(float)
energy_use['KWH PER SQFT'] = energy_use['TOTAL KWH']/energy_use['KWH TOTAL SQFT']

# THERMS PER SQFT
energy_use['TOTAL THERMS'] = energy_use['TOTAL THERMS'].str.replace(',', '').astype(float)
energy_use['THERMS TOTAL SQFT'] = energy_use['THERMS TOTAL SQFT'].str.replace(',', '').astype(float)
energy_use['THERMS PER SQFT'] = energy_use['TOTAL THERMS']/energy_use['THERMS TOTAL SQFT']

# SEASONALITY CHECK
'''cols = list(energy_use.columns)
kwh_list = []
for mo in range(4, 16):
    kwh_mo = energy_use[cols[mo]].str.replace(',', '').astype(float)
    series = kwh_mo/energy_use['KWH TOTAL SQFT']
    average = series.mean()
    kwh_list.append(average)

therms_list = []
for mo in range(19, 31):
    therm_mo = energy_use[cols[mo]].str.replace(',', '').astype(float)
    series = therm_mo/energy_use['THERMS TOTAL SQFT']
    average = series.mean()
    therms_list.append(average)

months_avgs = pd.DataFrame({
    'Month': ['jan', 'feb', 'mar', 'april','may',
              'june','july','aug', 'sept', 'oct','nov','dec'],
    'KWH': kwh_list,
    'THERMS': therms_list,
})'''
# OUTCOME
# Found that highest KWH per SQFT is in July, lowest in April
# Found that highest THERMS per SQFT is in January, lowest in August

energy_use["THERM SPREAD"] = (energy_use['THERM JANUARY 2010'].str.replace(',', '').astype(float) - energy_use[
                                    'THERM AUGUST 2010'].str.replace(',', '').astype(float))/energy_use['THERMS TOTAL SQFT']
energy_use["KWH SPREAD"] = (energy_use['KWH JULY 2010'].str.replace(',', '').astype(float) - energy_use[
                                    'KWH APRIL 2010'].str.replace(',', '').astype(float))/energy_use['KWH TOTAL SQFT']

"""Energy Efficiency Measures Are:
THERM SPREAD - THIS IS MORE IMPORTANT/RELEVANT
KWH SPREAD
THERMS PER SQFT
KWH PER SQFT - THIS IS MORE IMPORTANT/RELEVANT"""

# AGGREGATE MEASURES BETWEEN RESIDENTIAL HOUSE TYPES TO BLOCKWIDE
# Only occupied properties
energy_use['OCCUPIED HOUSING UNITS'] = energy_use['OCCUPIED HOUSING UNITS'].str.replace(',', '').astype(float)
energy_use['OCCUPIED HOUSING UNITS'] = energy_use['OCCUPIED HOUSING UNITS'].fillna(0)
energy_use = energy_use[~(energy_use['OCCUPIED HOUSING UNITS']==0)]

def therm_weighted(x):
    return np.average(x, weights=energy_use.loc[x.index, 'THERMS TOTAL SQFT'])
def kwh_weighted(x):
    return np.average(x, weights=energy_use.loc[x.index, 'KWH TOTAL SQFT'])

energy_use['TOTAL POPULATION'] = energy_use['TOTAL POPULATION'].str.replace(',', '').astype(float)

energy_use_cb = energy_use.groupby('CENSUS BLOCK').agg(
    THERM_SPREAD=('THERM SPREAD', therm_weighted),
    THERMS_PER_SQFT = ('THERMS PER SQFT', therm_weighted),
    THERMS_BUILDING_AGE = ('AVERAGE BUILDING AGE', therm_weighted),
    KWH_SPREAD = ('KWH SPREAD', kwh_weighted),
    KWH_PER_SQFT = ('KWH PER SQFT', kwh_weighted),
    KWH_BUILDING_AGE = ('AVERAGE BUILDING AGE', kwh_weighted),
    PCT_RENT = ('RENTER-OCCUPIED HOUSING PERCENTAGE', np.mean),
    POPULATION = ('TOTAL POPULATION', np.mean),
    THERMS_SQFT = ('THERMS TOTAL SQFT', np.sum),
    KWH_SQFT = ('KWH TOTAL SQFT', np.sum)
)

energy_use_cb.reset_index(inplace=True)

# Add back community areas
comm_areas = energy_use[['COMMUNITY AREA NAME', 'CENSUS BLOCK']]
comm_areas = comm_areas.drop_duplicates(subset=['CENSUS BLOCK'])
energy_use_cb = pd.merge(energy_use_cb, comm_areas, 
                         on='CENSUS BLOCK', how='left')


# INCOME DATA FROM CENSUS
med_incs = pd.read_csv('data/cleaned/ACS_Data_Clean.csv')

# EXTRACT CENSUS TRACT ID
med_incs['TRACT ID'] = med_incs['GEO_ID'].str[-6:]

energy_use_cb['CENSUS BLOCK'] = energy_use_cb['CENSUS BLOCK'].astype(int).astype(str)
energy_use_cb['TRACT ID'] = energy_use_cb['CENSUS BLOCK'].str[5:11]

# COMBINE
energy_use_cb = pd.merge(energy_use_cb, med_incs, on="TRACT ID", how='left')
energy_use_cb['Med_Inc_HH'] = energy_use_cb['Med_Inc_HH'].astype(int)

# AGGREGATE TO COMMUNITY AREA LEVEL

energy_use_cb = energy_use_cb.fillna(0)

def therm_weighted_cb(x):
    return np.average(x, weights=energy_use_cb.loc[x.index, 'THERMS_SQFT'])
def kwh_weighted_cb(x):
    return np.average(x, weights=energy_use_cb.loc[x.index, 'KWH_SQFT'])
def pop_weighted_cd(x):
    return np.average(x, weights=energy_use_cb.loc[x.index, 'POPULATION'])

energy_use_ca = energy_use_cb.groupby('COMMUNITY AREA NAME').agg(
    THERM_SPREAD=('THERM_SPREAD', therm_weighted_cb),
    THERMS_PER_SQFT = ('THERMS_PER_SQFT', therm_weighted_cb),
    THERMS_BUILDING_AGE = ('THERMS_BUILDING_AGE', therm_weighted_cb),
    KWH_SPREAD = ('KWH_SPREAD', kwh_weighted_cb),
    KWH_PER_SQFT = ('KWH_PER_SQFT', kwh_weighted_cb),
    KWH_BUILDING_AGE = ('KWH_BUILDING_AGE', kwh_weighted_cb),
    PCT_RENT = ('PCT_RENT', pop_weighted_cd),
    MED_INC = ('Med_Inc_HH', pop_weighted_cd),
    POPULATION = ('POPULATION', np.sum),
    THERMS_SQFT = ('THERMS_SQFT', np.sum),
    KWH_SQFT = ('KWH_SQFT', np.sum)
)

energy_use_ca = energy_use_ca.reset_index()

# ADD GEOGRAPHY
community = pd.read_csv('data/external/Chicago_CommunityAreas.csv')

community['COMMUNITY'] = community['COMMUNITY'].str.lower()
energy_use_ca['COMMUNITY AREA NAME'] = energy_use_ca['COMMUNITY AREA NAME'].str.lower()
community = community.rename(columns={'COMMUNITY': 'COMMUNITY AREA NAME'})

renaming = {
    'lakeview':'lake view',
    'o\'hare': 'ohare'
}
energy_use_ca['COMMUNITY AREA NAME'] = energy_use_ca['COMMUNITY AREA NAME'].replace(renaming)

energy_use_ca = pd.merge(energy_use_ca, community, on="COMMUNITY AREA NAME").rename(columns={'the_geom':'geometry'})

# CLEANING UP
energy_use_ca['Building_Age'] = (energy_use_ca['THERMS_BUILDING_AGE']+energy_use_ca['KWH_BUILDING_AGE'])/2
energy_use_ca = energy_use_ca[['COMMUNITY AREA NAME', 'THERM_SPREAD', 'THERMS_PER_SQFT',
        'KWH_SPREAD', 'KWH_PER_SQFT', 
       'PCT_RENT', 'MED_INC', 'Building_Age', 'POPULATION', 'THERMS_SQFT', 'KWH_SQFT',
       'geometry']]

renaming = {
    'lake view': 'lakeview',
    'ohare': 'o\'hare'
}

energy_use_ca['COMMUNITY AREA NAME'] = energy_use_ca['COMMUNITY AREA NAME'
                                                     ].replace(renaming).str.title()

# MAKE QUARTILES FOR HEATMAPPING

flip_map = {
    1: 5,
    2: 4,
    3: 3,
    4: 2,
    5: 1
}

energy_use_ca['RENTER_Q'] = pd.qcut(energy_use_ca['PCT_RENT'],q=5, labels=False)+1
energy_use_ca['HOMEOWNER_Q'] = energy_use_ca['RENTER_Q'].replace(flip_map)
energy_use_ca['OLD_BUILD_Q'] = pd.qcut(energy_use_ca['Building_Age'],q=5, labels=False)+1
energy_use_ca['NEW_BUILD_Q'] = energy_use_ca['OLD_BUILD_Q'].replace(flip_map)
energy_use_ca['HIGH_INC_Q'] = pd.qcut(energy_use_ca['MED_INC'],q=5, labels=False)+1
energy_use_ca['LOW_INC_Q'] = energy_use_ca['HIGH_INC_Q'].replace(flip_map)
energy_use_ca['HEAT_LEAK_Q'] = pd.qcut(energy_use_ca['THERM_SPREAD'],q=5, labels=False)+1
energy_use_ca['ENERGY_WASTE_Q'] = pd.qcut(energy_use_ca['KWH_PER_SQFT'],q=5, labels=False)+1

#FINAL DF is ENERGY_USE_CA
```


## Outcome

So, what neighborhoods does the Green Homes Chicago Program target, and do these neighborhoods have the worst energy efficiency? The following scatter plot shows median income against the percent of renter population for each community area. The plot shows that as renter population deacreases income tends to increase. Additionally, the color shows a clear pattern that worse energy efficiency outcomes, as indicated by the seasonal difference in gas use, occur more often for lower income communitites, but there does not seem to be a correlation on renter composition of community areas. 

```{python}
#| eval: true
#| echo: false

chart = alt.Chart(energy_use_ca).mark_circle(size=50).encode(
    x=alt.X('MED_INC:Q', title="Median Income"),
    y=alt.Y('PCT_RENT:Q', title="Renter Percentage"),
    color=alt.Color('THERM_SPREAD:Q', scale=alt.Scale(scheme='viridis'), title=["Seasonal Difference", "in Gas Use", "(Therms per SQFT)"])
)
display(chart)
```

A simple scatter plot of renter composition and the energy efficiency metric, provided in the dashboard below, shows that there is in fact a correlation between homeownership and poor energy efficiency. It appears that the Green Homes Chicago program appropriately targets grantees!

The neighborhoods that would benefit the most from these programs are on the south and west sides based on a priority score. More information on how the priority score is calculated can be found in the dashboard below.

```{python}
#| eval: true
#| echo: false

energy_use_ca['geometry'] = energy_use_ca['geometry'].apply(wkt.loads)
city = gpd.GeoDataFrame(energy_use_ca, geometry='geometry', crs='EPSG:23304')

energy_measure = 'HEAT_LEAK_Q'
rent_measure = 'HOMEOWNER_Q'
income_measure = 'LOW_INC_Q'
city['HIGHLIGHT'] = city[energy_measure]+city[rent_measure]+city[income_measure]


ax = city.plot(
    column='HIGHLIGHT',
    cmap='OrRd',
    edgecolor='grey',
    legend=True,
    legend_kwds={'label': 'Outreach Priority', 'orientation': 'vertical'},
    figsize=(10, 6)
)
ax.set_axis_off()
ax.set_title("Green Homes Chicago Outreach Priority Map", weight='bold', fontsize=13)
plt.show()

```

## Streamlit App

A dynamic dashboard allows officials to explore different constructions of energy efficiency plans.

[Check out the dashboard here!](https://dap-final-chicago-energy.streamlit.app/) 